import { Pokemon } from "../types/pokemon";

export const POKEMONS: Pokemon[] = [
    {
        id: 1,
        nombre: "Bulbasaur",
        peso: 69,
        altura: 7,
        tipos: ["planta", "veneno"],
        indice: 1,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    },
    {
        id: 4,
        nombre: "Charmander",
        peso: 85,
        altura: 6,
        tipos: ["fuego"],
        indice: 4,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
    },
    {
        id: 7,
        nombre: "Squirtle",
        peso: 90,
        altura: 5,
        tipos: ["agua"],
        indice: 7,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
    },
    {
        id: 25,
        nombre: "Pikachu",
        peso: 60,
        altura: 4,
        tipos: ["eléctrico"],
        indice: 25,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    },
    {
        id: 39,
        nombre: "Jigglypuff",
        peso: 55,
        altura: 5,
        tipos: ["normal", "hada"],
        indice: 39,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
    },
    {
        id: 94,
        nombre: "Gengar",
        peso: 405,
        altura: 15,
        tipos: ["fantasma", "veneno"],
        indice: 94,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
    },
    {
        id: 133,
        nombre: "Eevee",
        peso: 65,
        altura: 3,
        tipos: ["normal"],
        indice: 133,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
    },
    {
        id: 150,
        nombre: "Mewtwo",
        peso: 1220,
        altura: 20,
        tipos: ["psíquico"],
        indice: 150,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
    },
    {
        id: 151,
        nombre: "Mew",
        peso: 40,
        altura: 4,
        tipos: ["psíquico"],
        indice: 151,
        icon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
    }
];